# Pakiet numpy I

**Zadanie 1**
Utwórz zwykłą listę miliona liczb całkowitych i ich odpowiednik w `numpy` składający się z takich samych liczb z wykorzystaniem `np.arange()`. Wykonaj $10$-krotne mnożenie elementów tych sekwencji (tj. stwórz nowe obiekty tego typu o podwojonych wartościach) przez $2$ i zmierz czas tej operacji używając dyrektywy `%timeit`.

In [3]:

import numpy as np

python_list = list(range(1000000))

numpy_array = np.arange(1000000)

print("Czas mnożenia listy przez 2 (10 razy):")
%timeit for _ in range(10): new_python_list = [x * 2 for x in python_list]

print("\nCzas mnożenia tablicy numpy przez 2 (10 razy):")
%timeit for _ in range(10): new_numpy_array = numpy_array * 2


Czas mnożenia listy przez 2 (10 razy):
728 ms ± 12.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Czas mnożenia tablicy numpy przez 2 (10 razy):
12.1 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


**Zadanie 2**
Oceń które, z poniższych operacji da się wykonać. Jeżeli operacja jest wykonywalna to wyznacz kształt wyniku.
* `np.array([[1,2,3], [4,5,6]]) * np.array([[1,2], [4,5]])`
* `np.array([[1,2,3], [4,5,6], [7,8,9]]) * np.array([[1], [2], [3]])`
* `np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10]]) * np.arange(1,13).reshape(1,1,3,4)`
* `np.array([[1,2], [3,4], [5,6], [7, 8]]) + np.arange(1,9).reshape(1,4,2)`

In [4]:
print("Operacja 1:")
try:
  result = np.array([[1,2,3], [4,5,6]]) * np.array([[1,2], [4,5]])
  print("Nie można wykonać tej operacji. Wymiary macierzy nie są zgodne.")
except ValueError:
  print("Nie można wykonać tej operacji. Wymiary macierzy nie są zgodne.")

print("\nOperacja 2:")
try:
  result = np.array([[1,2,3], [4,5,6], [7,8,9]]) * np.array([[1], [2], [3]])
  print("Można wykonać operację.")
  print("Kształt wyniku:", result.shape)
except ValueError:
  print("Nie można wykonać tej operacji. Wymiary macierzy nie są zgodne.")

print("\nOperacja 3:")
try:
  result = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,10]]) * np.arange(1,13).reshape(1,1,3,4)
  print("Można wykonać operację.")
  print("Kształt wyniku:", result.shape)
except ValueError:
  print("Nie można wykonać tej operacji. Wymiary macierzy nie są zgodne.")

print("\nOperacja 4:")
try:
  result = np.array([[1,2], [3,4], [5,6], [7, 8]]) + np.arange(1,9).reshape(1,4,2)
  print("Można wykonać operację.")
  print("Kształt wyniku:", result.shape)
except ValueError:
  print("Nie można wykonać tej operacji. Wymiary macierzy nie są zgodne.")



Operacja 1:
Nie można wykonać tej operacji. Wymiary macierzy nie są zgodne.

Operacja 2:
Można wykonać operację.
Kształt wyniku: (3, 3)

Operacja 3:
Można wykonać operację.
Kształt wyniku: (1, 1, 3, 4)

Operacja 4:
Można wykonać operację.
Kształt wyniku: (1, 4, 2)


**Zadanie 3**
Niech będzie dana macierz o $150$ wierszach i $4$ kolumnach, utworzona w następujący sposób.
```python
import seaborn as sns
iris = np.array(sns.load_dataset("iris").iloc[:,0:4])
```
Dokonaj standaryzacji wszystkich zmiennych, tj. w każdej kolumnie od każdej obserwacji odejmij wartości średniej arytmetycznej i podziel ją przez odchylenie standardowe.

In [5]:
import numpy as np
import seaborn as sns

iris = np.array(sns.load_dataset("iris").iloc[:,0:4])

means = np.mean(iris, axis=0)
stds = np.std(iris, axis=0)
standardized_iris = (iris - means) / stds

print(standardized_iris)


[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

**Zadanie 4**
Zaimplementuj funkcję, która dla danego wektora $\mathbf{x}$ o długości $d$ oraz nieparzystej liczby naturalnej $k$ wyznaczy $k$-średnią ruchomą, $k < d$, tj. taki wektor $(w_1,\dots,w_{d-k+1})$, że:
$$w_i =\sum_{j=1}^{k}\frac{x_{i+j-1}}{k}$$

Przykładowo:
* dla tablicy `array([1, 2, 3, 4, 5, 6])` i `k = 3` rozwiązaniem jest `array([2., 3., 4., 5.])`

In [6]:

import numpy as np
import seaborn as sns

def moving_average(x, k):
  if k % 2 == 0 or k >= len(x):
    raise ValueError("k musi być liczbą nieparzystą mniejszą od długości wektora x.")

  result = []
  for i in range(len(x) - k + 1):
    window = x[i:i+k]
    result.append(np.mean(window))

  return np.array(result)

x = np.array([1, 2, 3, 4, 5, 6])
k = 3
moving_average_result = moving_average(x, k)
print(moving_average_result)


[2. 3. 4. 5.]


**Zadanie 5**

> Dodaj cytat blokowy


Zaimplementuj algorytm sortowanie szybkiego wektorów wykorzystując funkcję/metodę `partition()`.

In [7]:
def quick_sort_numpy(arr):
    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr) // 2]
    left = arr[arr < pivot]
    middle = arr[arr == pivot]
    right = arr[arr > pivot]

    return np.concatenate((quick_sort_numpy(left), middle, quick_sort_numpy(right)))

arr = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
sorted_arr = quick_sort_numpy(arr)
print(sorted_arr)


[1 2 3 4 5 6 7 8 9]


**Zadanie 6**
Niech będzie dany wektor
```python
y = np.random.randint(0, 101, 50)
```
Wybierz z wektora $y$ wszystkie elementy, które należą do przedizalu $[25, 75]$. Uzyj ideksowania przy użyciu wektora logicznego!

In [8]:
y = np.random.randint(0, 101, 50)

elements_in_range = y[(y >= 25) & (y <= 75)]

print(elements_in_range)


[49 66 45 32 44 73 57 68 25 56 29 65 48 61 66 64 41 31 51 58 39 63 44 34]


**Zadanie 7**
Napisz funkcję, która wywołując `unique()` (z odpowiednimi argumentami), wyznacza modę (dominantę) wartości w podanym wektorze.

In [9]:
def mode_numpy(arr):
  values, counts = np.unique(arr, return_counts=True)
  mode = values[np.argmax(counts)]
  return mode

arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
mode = mode_numpy(arr)
print(f"Moda wektora: {mode}")


Moda wektora: 4


**Zadanie 8**
Stwórz dwie macierze $3\times 3$ (o nazwach `A` i `B`) z losowymi wartościami z zakresu $1-10$. Wykonaj na nich następujące operacje:
* dodaj macierze `A` i `B`;
* pomnóż macierze `A` i `B element po elemencie;
* oblicz iloczyn macierzy (`A @ B`);
* transponuj macierz `A`.

In [10]:
A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

print("Macierz A:")
print(A)
print("\nMacierz B:")
print(B)

sum_AB = A + B
print("\nSuma macierzy A i B:")
print(sum_AB)

elementwise_product_AB = A * B
print("\nMnożenie macierzy A i B element po elemencie:")
print(elementwise_product_AB)

matrix_product_AB = A @ B
print("\nIloczyn macierzy A i B:")
print(matrix_product_AB)

transpose_A = A.T
print("\nTranspozycja macierzy A:")
print(transpose_A)


Macierz A:
[[ 8  8 10]
 [ 3  2  2]
 [ 8  5  7]]

Macierz B:
[[ 5  9  6]
 [ 9 10  9]
 [ 2  1  7]]

Suma macierzy A i B:
[[13 17 16]
 [12 12 11]
 [10  6 14]]

Mnożenie macierzy A i B element po elemencie:
[[40 72 60]
 [27 20 18]
 [16  5 49]]

Iloczyn macierzy A i B:
[[132 162 190]
 [ 37  49  50]
 [ 99 129 142]]

Transpozycja macierzy A:
[[ 8  3  8]
 [ 8  2  5]
 [10  2  7]]


**Zadanie 9**
Utwórz jednowymiarową tablicę `x` o długości $20,$ składającą się z liczb od $1$ do $20$. Wykonaj następujące operacje:
* wyciągnij z tablicy `x` elementy z indeksów od $4$ do $16$;
* zwróć wszystkie elementy większe niż $8$;
* zmień wszystkie elementy o wartościach podzielnych przez $3$  na $100$.   

In [11]:
x = np.arange(1, 21)

elements_from_4_to_16 = x[4:17]
print("Elementy z indeksów od 4 do 16:", elements_from_4_to_16)

elements_greater_than_8 = x[x > 8]
print("Elementy większe niż 8:", elements_greater_than_8)

x[x % 3 == 0] = 100
print("Tablica x po zmianie elementów podzielnych przez 3 na 100:", x)


Elementy z indeksów od 4 do 16: [ 5  6  7  8  9 10 11 12 13 14 15 16 17]
Elementy większe niż 8: [ 9 10 11 12 13 14 15 16 17 18 19 20]
Tablica x po zmianie elementów podzielnych przez 3 na 100: [  1   2 100   4   5 100   7   8 100  10  11 100  13  14 100  16  17 100
  19  20]


**Zadanie 10**
Stwórz wektor z losowymi liczbami całkowitymi z zakresu od $1$ do $100$ (np. $50$ elementów) i wykonaj na niej następujące operacje:
* oblicz średnią, medianę i odchylenie standardowe;
* znajdź minimalną i maksymalną wartość;
* posortuj tablicę rosnąco.

In [12]:
vector = np.random.randint(1, 101, 50)

mean = np.mean(vector)
median = np.median(vector)
std = np.std(vector)

print("Średnia:", mean)
print("Mediana:", median)
print("Odchylenie standardowe:", std)

min_value = np.min(vector)
max_value = np.max(vector)

print("Minimalna wartość:", min_value)
print("Maksymalna wartość:", max_value)

sorted_vector = np.sort(vector)

print("Posortowany wektor:", sorted_vector)


Średnia: 49.34
Mediana: 47.0
Odchylenie standardowe: 29.692834152367467
Minimalna wartość: 1
Maksymalna wartość: 100
Posortowany wektor: [  1   1   4   7   8   9  11  17  17  18  24  25  26  27  29  30  30  30
  33  33  35  35  40  47  47  47  52  54  55  60  61  61  64  68  69  72
  75  77  77  78  84  86  87  87  87  93  96  96  97 100]


**Zadanie 11**
Utwórz tablicę $5\times5$ wypełnioną wartościami z rozkładu normalnego i wykonaj na niej następujące operacje:
* oblicz sumę wartości dla każdego wiersza;
* oblicz sumę wartości dla każdej kolumny;
* znajdź indeksy wartości maksymalnej dla całej tablicy;
* zastosuj macierz logiczną, aby znaleźć wszystkie wartości większe niż $0.5$;
* zastąp wszystkie wartości mniejsze niż $-0.5$ lub większe od $0.5$ liczbą $0$.

In [13]:
import numpy as np

array = np.random.randn(5, 5)

print("Tablica:")
print(array)

row_sums = np.sum(array, axis=1)
print("\nSuma wartości dla każdego wiersza:")
print(row_sums)

column_sums = np.sum(array, axis=0)
print("\nSuma wartości dla każdej kolumny:")
print(column_sums)

max_value_indices = np.unravel_index(np.argmax(array), array.shape)
print("\nIndeksy wartości maksymalnej:")
print(max_value_indices)

values_greater_than_0_5 = array[array > 0.5]
print("\nWartości większe niż 0.5:")
print(values_greater_than_0_5)

array[(array < -0.5) | (array > 0.5)] = 0
print("\nTablica po zastąpieniu wartości mniejszych niż -0.5 lub większych od 0.5 liczbą 0:")
print(array)


Tablica:
[[-0.24132586 -1.26364873  0.34353975 -1.04348777  1.36754008]
 [ 0.79736101 -1.39654696 -1.1389966  -0.1916287   0.20813222]
 [ 0.621874    0.6170469   0.24945617  1.48934223  1.32166001]
 [-0.94370945 -0.39771287 -1.2937106   0.62870293 -1.53277726]
 [ 1.11966889  1.98274525  1.75609717  1.22242169 -0.01915246]]

Suma wartości dla każdego wiersza:
[-0.83738253 -1.72167904  4.2993793  -3.53920725  6.06178053]

Suma wartości dla każdej kolumny:
[ 1.35386858 -0.45811641 -0.08361411  2.10535038  1.34540258]

Indeksy wartości maksymalnej:
(4, 1)

Wartości większe niż 0.5:
[1.36754008 0.79736101 0.621874   0.6170469  1.48934223 1.32166001
 0.62870293 1.11966889 1.98274525 1.75609717 1.22242169]

Tablica po zastąpieniu wartości mniejszych niż -0.5 lub większych od 0.5 liczbą 0:
[[-0.24132586  0.          0.34353975  0.          0.        ]
 [ 0.          0.          0.         -0.1916287   0.20813222]
 [ 0.          0.          0.24945617  0.          0.        ]
 [ 0.         -0.3

**Zadanie 12**
Utwórz funkcję funkcję $f(x) = x^3 - 2x + 1$. Użyj `numpy.vectorize()`, aby zmapować tę funkcję na tablicę jednowymiarową o wartościach od $-5$ do $5$.

In [14]:
def f(x):
  return x**3 - 2*x + 1

x = np.arange(-5, 6)
vectorized_f = np.vectorize(f)
result = vectorized_f(x)

print(result)


[-114  -55  -20   -3    2    1    0    5   22   57  116]


**Zadanie 13**
Dokonaj wektoryzacji własnej funkcji wyznaczające największy wspólny dzielnik. Wyznacza macierz największych wspólnych dzielników dla utworzonych tablic `A` i `B` o wymiarach $5\times5$. Macierz `A` ma zawierać liczby losowe z zakresu $20 - 100$ a macierz `A` liczby z zakresu $2-20$. Oblicz liczbę wartości równych $1$ w macierzy dzielników.

In [15]:
import seaborn as sns

def gcd(a, b):
  if b == 0:
    return a
  return gcd(b, a % b)

vectorized_gcd = np.vectorize(gcd)

A = np.random.randint(20, 101, size=(5, 5))
B = np.random.randint(2, 21, size=(5, 5))

gcd_matrix = vectorized_gcd(A, B)

number_of_ones = np.sum(gcd_matrix == 1)

print("Macierz A:")
print(A)
print("\nMacierz B:")
print(B)
print("\nMacierz największych wspólnych dzielników:")
print(gcd_matrix)
print("\nLiczba wartości równych 1 w macierzy dzielników:", number_of_ones)


Macierz A:
[[89 70 59 40 69]
 [56 21 50 27 46]
 [95 38 61 45 80]
 [55 97 40 47 98]
 [86 24 38 51 35]]

Macierz B:
[[15 17 18 16  7]
 [20  2 13 15  3]
 [ 8 12 15 14  6]
 [18 12 19 10 11]
 [10  2  7 18  3]]

Macierz największych wspólnych dzielników:
[[1 1 1 8 1]
 [4 1 1 3 1]
 [1 2 1 1 2]
 [1 1 1 1 1]
 [2 2 1 3 1]]

Liczba wartości równych 1 w macierzy dzielników: 17


**Zadanie 14**
Stwórz dwie tablice 2D o wymiarach $2\times 3$ i wykonaj następujące operacje:
* połącz obie tablice wzdłuż osi poziomej (oś `0`);
* połącz obie tablice wzdłuż osi pionowej (oś `1`);
* podziel wynikową tablicę z pkt 1 na dwie równe części wzdłuż osi poziomej (znajdź odpowiednią metodę).

In [16]:

array1 = np.random.randint(1, 10, size=(2, 3))
array2 = np.random.randint(1, 10, size=(2, 3))

print("Tablica 1:")
print(array1)
print("\nTablica 2:")
print(array2)

horizontal_concat = np.concatenate((array1, array2), axis=0)
print("\nPołączenie wzdłuż osi poziomej:")
print(horizontal_concat)

vertical_concat = np.concatenate((array1, array2), axis=1)
print("\nPołączenie wzdłuż osi pionowej:")
print(vertical_concat)

split_arrays = np.split(horizontal_concat, 2, axis=0)
print("\nPodział wynikowej tablicy na dwie równe części wzdłuż osi poziomej:")
print(split_arrays)


Tablica 1:
[[4 3 2]
 [9 9 5]]

Tablica 2:
[[5 4 5]
 [5 4 7]]

Połączenie wzdłuż osi poziomej:
[[4 3 2]
 [9 9 5]
 [5 4 5]
 [5 4 7]]

Połączenie wzdłuż osi pionowej:
[[4 3 2 5 4 5]
 [9 9 5 5 4 7]]

Podział wynikowej tablicy na dwie równe części wzdłuż osi poziomej:
[array([[4, 3, 2],
       [9, 9, 5]]), array([[5, 4, 5],
       [5, 4, 7]])]


**Zadanie 15**
Stwórz dwie macierze $6\times 6$, o losowych wwartościach całkowitych z zakresu od $1-9$. Macierze o takich wymiarach można podzielić na mniejsze bloki $2\times 2$. Napisz kod, który mnoży (element po elemencie) odpowiadające sobie bloki w macierzach i zapisuje wynik w nowej macierzy $6\times 6$. Nie chodzi o zwykłe mnożenie dwóch całych macierzy o wymiarach $6\times 6$ przez siebie - choć wynik będzie identyczny!!!

In [17]:
matrix1 = np.random.randint(1, 10, size=(6, 6))
matrix2 = np.random.randint(1, 10, size=(6, 6))

result_matrix = np.zeros((6, 6))

for row in range(0, 6, 2):
  for col in range(0, 6, 2):
    block1 = matrix1[row:row+2, col:col+2]
    block2 = matrix2[row:row+2, col:col+2]
    result_matrix[row:row+2, col:col+2] = block1 * block2

print("Macierz 1:")
print(matrix1)
print("\nMacierz 2:")
print(matrix2)
print("\nMacierz wynikowa (mnożenie bloków):")
print(result_matrix)


Macierz 1:
[[3 2 8 2 7 3]
 [1 4 9 2 6 3]
 [6 3 1 6 6 6]
 [4 1 4 1 2 6]
 [6 4 7 6 7 1]
 [9 6 7 3 7 3]]

Macierz 2:
[[6 5 8 1 4 9]
 [4 6 7 8 9 4]
 [6 2 6 1 4 2]
 [9 1 9 1 9 2]
 [5 4 1 1 8 4]
 [7 8 6 7 1 3]]

Macierz wynikowa (mnożenie bloków):
[[18. 10. 64.  2. 28. 27.]
 [ 4. 24. 63. 16. 54. 12.]
 [36.  6.  6.  6. 24. 12.]
 [36.  1. 36.  1. 18. 12.]
 [30. 16.  7.  6. 56.  4.]
 [63. 48. 42. 21.  7.  9.]]


**Zadanie 16**
Używając metody Monte Carlo, aproksymuj wartość liczby $pi$. Zaimplementuj to za pomocą losowego generowania punktów w kwadracie $[-1, 1]\times [-1, 1]$, a następnie sprawdź, ile z tych punktów znajduje się wewnątrz  koła o promieniu $1$.

In [19]:
def approximate_pi(num_points):
  x = np.random.uniform(-1, 1, num_points)
  y = np.random.uniform(-1, 1, num_points)

  inside_circle = (x**2 + y**2) <= 1
  num_points_inside = np.sum(inside_circle)

  pi_approximation = 4 * (num_points_inside / num_points)
  return pi_approximation

num_points = 1000000
pi_approximation = approximate_pi(num_points)

print(f"Aproksymacja liczby pi: {pi_approximation}")


Aproksymacja liczby pi: 3.14128
